export const presta = [
  {
    id: 1,
    name: "Naissance",
    description: "Immortalisez les premiers sourires de vos bébés.",
    price: "À partir de 230€",
    src: "/images/naissance.png",
    info: "Afin de s'adapter au besoin de bébé, il faut compter 2 à 3h pour une séance.",
    forfait1: ["Séance bébé seul & parents", "230€", "10 photos"],
    forfait2: ["Séance bébé seul & parents", "275€", "15 photos"],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Je me déplace chez vous, avec du matériel (paniers, duvets, coussins, linges ...) et des décors.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).",
      "Vous en voulez toujours plus ? Vous avez la possibilité d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
    ],
  },
  {
    id: 2,
    name: "Grossesse",
    description: "Gardez des souvenirs inoubliables de votre grossesse.",
    price: "À partir de 170€",
    src: "/images/grossesse.png",
    info: "La séance se déroule en intérieur ou en extérieur selon vos envies.",
    forfait1: ["Forfait 1", "170€", "10 photos"],
    forfait2: ["Forfait 2", "215€", "15 photos"],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Nous avons la possibilité d'aller le long de la mer au coucher ou au lever du soleil pour un supplément de 50€.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).",
      "Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
    ],
  },
  {
    id: 3,
    name: "Couple, famille, solo",
    description: "Figez les moments de vie de façon authentique et naturelle.",
    price: "À partir de 170€",
    src: "/images/couple.png",
    info: "La séance se réalise en intérieur ou en extérieur, selon vos envies (et parfois la saison).",
    forfait1: ["Forfait 1", "170€", "10 photos"],
    forfait2: ["Forfait 2", "215€", "15 photos"],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).  ",
      "Vous en souhaitez davantage ? Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
    ],
  },
  {
    id: 4,
    name: "Animaux de compagnie",
    description:
      "Parce que nos boules de poils ont le droit aussi à leur séance photo !",
    price: "À partir de 90€",
    src: "/images/animaux.png",
    info: "Pour nos amis poilus et leurs parents !",
    forfait1: ["Forfait tout doux", "90€", "5 photos"],
    forfait2: ["Forfait petit plaisir", "135€", "10 photos"],
    forfait3: ["Forfait gros plaisir", "180€", "15 photos"],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Il faut compter environ 1h pour une séance.",
      "La séance peut se réaliser en intérieur ou en extérieur.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).",
      "Vous n'en avez pas assez ? Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
    ],
  },
  {
    id: 5,
    name: "Baptême",
    description: "Capturez les moments précieux de vos enfants.",
    price: "À partir de 500€",
    src: "/images/bapteme.png",
    info: "Pour les baptêmes ou les anniversaires.",
    forfait1: [
      `Forfait "Smile" : 3h`,
      "500€",
      "50 photos + 1 tirage 13x18 offert ",
    ],
    forfait2: [
      `Forfait "Fiesta" : 4h `,
      "600€",
      "65 photos 1 tirage offert 18x24",
    ],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
      "Pour toute autre demande, n'hésitez pas à me contacter.",
    ],
  },
  {
    id: 6,
    name: "Mariage",
    description: `Tout simplement car c'est le "Plus beau jour de votre vie".`,
    price: "À partir de 500€",
    src: "/images/mariage.png",
    info: "Pour votre mariage, je viendrai vous rencontrer avant le grand jour, afin de répondre au mieux à vos souhaits.",
    forfait1: [
      `Forfait "Elégance"
        : Mairie, lieu de culte, et vin d'honneur (3h de présence).`,
      "500€",
      "50 photos + 1 tirage 13x18 offert",
    ],
    forfait2: [
      `Forfait "Prestige" : Journée complète (préparation de la mariée, mairie, lieu de culte, et vin d'honneur) `,
      "700€",
      "80 photos 1 tirage 18x24 offert",
    ],
    forfait3: [
      `Forfait "Excellence" : Des préparatifs jusqu'à la soirée dansante`,
      "2000€",
      "300 photos",
    ],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km). ",
      "Les photos seront disponibles en HD dans un délai de 1 mois. Elles seront envoyées sur une clé USB directement à votre domicile.",
      "Pour toute autre demande, n'hésitez pas à me contacter.",
    ],
  },
  {
    id: 7,
    name: "Les séances Boudoir",
    description:
      "Pour le plaisir de se faire plaisir ! Osez une séance Boudoir pour révéler votre beauté.",
    price: "À partir de 170€",
    src: "/images/boudoir.png",
    forfait1: ["Forfait 1", "170€", "10 photos"],
    forfait2: ["Forfait 2", "215€", "15 photos"],
    info: "La séance se réalise en intérieur, pour garder toute l'intimité de ce moment. Nous échangeons quelques temps avant de commencer la séance. La séance boudoir offre un moment de temps suspendu et de déconnexion. Elle met en valeur le corps humain à travers des jeux de lumières.",
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (0,3€/km).",
      "Les photos seront disponibles en HD dans un délai d'un mois via une galerie en ligne.",
    ],
  },
  {
    id: 8,
    name: "Portrait professionnel",
    description:
      "Je vous accompagne et vous guide afin d'obtenir des portraits authentiques pour vos expériences professionnelles.",
    price: "(Devis personnalisé)",
    src: "/images/portrait.png",
    contact: [
      "Avant de réaliser la séance il est important que nous échangions par rapport à vos attentes et votre métier.",
      "Un devis personnalisé vous sera proposé après cet entretien.",
      "Je vous invite à remplir le formulaire de contact pour que je puisse en savoir plus.",
    ],
  },
  {
    id: 9,
    name: "Photographie culinaire",
    description: "Mise en valeur de votre entreprise et de vos réalisations. ",
    price: "(Devis personnalisé)",
    src: "/images/culinaire.png",
    contact: [
      "Les tarifs se font sur devis après un entretien téléphonique. Cela permet de répondre au mieux a vos attentes.",
      "Je vous invite à remplir le formulaire de contact. ",
    ],
  },
  {
    id: 10,
    name: "Bain thérapeutique photogtraphié",
    price: "À partir de 150€",
    src: "/images/culinaire.png",
    forfait1: ["Séance 10 photos bébé & parents", "180€"],
    info: "La séance se déroule à Rivery avec Hyn'Odysée bien naître et dure environ 1h30 parfois plus selon bébé.",
    contact: [
      "Le bain thérapeutique est un soin qui permet au bébé de retrouver les sensations connues de sa vie intra utérine. Emmailloté dans une eau chaude, il est libre de ses mouvements et retrouve le bien être du ventre maternel. Plongé dans ses souvenirs, le retrait du lange représente pour lui le moment de la naissance. Il refait le passage entre les deux mondes plus en douceur. Ce bain permet parfois de libérer des émotions pour le bébé et pour la maman , surtout lorsque l'accouchement n'est pas celui qui était souhaité...",
      "C'est Hélène qui s'occupera de réaliser le bain thérapeutique. Elle est auxiliaire de puérilculture en maternité et s'est formée à l'école du bien naître de Sonia Krief.",
    ],
  },
];
